use std::path::Path;

use crate::model::{Element, Id, Mesh};

use super::{
    element_group_name, ensure_output_folder, format_e6, ids_in_order, node_group_name, slice_ids,
    write_lines, AbaqusOptions, ExportResult, ExportedFiles,
};

pub fn export(
    mesh: &Mesh,
    output_folder: impl AsRef<Path>,
    output_file_name: &str,
    _options: AbaqusOptions,
) -> ExportResult<ExportedFiles> {
    let output_folder = output_folder.as_ref();
    ensure_output_folder(output_folder)?;
    let path = output_folder.join(format!("{output_file_name}.inp"));
    let path = write_lines(path, create_inp_lines(mesh)?)?;
    let mut files = ExportedFiles::default();
    files.push(path);
    Ok(files)
}

pub fn solid_mapping(element: &Element) -> Option<&'static [usize]> {
    match element.node_ids.len() {
        8 => Some(&[1, 2, 3, 4, 5, 6, 7, 8]),
        6 => Some(&[1, 2, 3, 3, 4, 5, 6, 6]),
        5 => Some(&[1, 2, 3, 4, 5, 5, 5, 5]),
        4 => Some(&[1, 2, 3, 3, 4, 4, 4, 4]),
        _ => None,
    }
}

pub fn shell_mapping(element: &Element) -> Option<&'static [usize]> {
    match element.node_ids.len() {
        4 => Some(&[1, 2, 3, 4]),
        3 => Some(&[1, 2, 3, 3]),
        _ => None,
    }
}

fn create_inp_lines(mesh: &Mesh) -> ExportResult<Vec<String>> {
    let mut lines = vec![
        "** ".to_owned(),
        "** Abaqus Mesh generated by MidasGtsExporter v20180405".to_owned(),
        "** ".to_owned(),
        "*Heading".to_owned(),
        "*Part, name=Part_MidasGts".to_owned(),
        "*Node, nset=nset_all_node".to_owned(),
    ];

    for node in mesh.nodes.values() {
        lines.push(format!(
            "{},{},{},{}",
            node.id,
            format_e6(node.x),
            format_e6(node.y),
            format_e6(node.z)
        ));
    }

    if !mesh.elements_3d.is_empty() {
        lines.push("*Element, type=C3D8R, elset=eset_3D".to_owned());
        for element in mesh.elements_3d.values() {
            if let Some(order) = solid_mapping(element) {
                lines.push(element_line(element.id, &ids_in_order(element, order)?));
            }
        }
    }

    if !mesh.elements_2d.is_empty() {
        lines.push("*Element, type=S4R, elset=eset_2D".to_owned());
        for element in mesh.elements_2d.values() {
            if let Some(order) = shell_mapping(element) {
                lines.push(element_line(element.id, &ids_in_order(element, order)?));
            }
        }
    }

    if !mesh.elements_1d.is_empty() {
        lines.push("*Element, type=B31, elset=eset_1D".to_owned());
        for element in mesh.elements_1d.values() {
            lines.push(element_line(element.id, &ids_in_order(element, &[1, 2])?));
        }
    }

    for (group_id, ids) in &mesh.node_groups {
        let group_name = node_group_name(&mesh.node_group_names[group_id]);
        lines.push(format!("*Nset, nset={group_name}"));
        lines.extend(slice_ids(ids, 16, ","));
    }
    for (group_id, ids) in &mesh.element_3d_groups {
        append_element_group(&mut lines, group_id, ids, mesh);
    }
    for (group_id, ids) in &mesh.element_2d_groups {
        append_element_group(&mut lines, group_id, ids, mesh);
    }
    for (group_id, ids) in &mesh.element_1d_groups {
        append_element_group(&mut lines, group_id, ids, mesh);
    }

    lines.push("*End Part".to_owned());
    Ok(lines)
}

fn append_element_group(lines: &mut Vec<String>, group_id: &Id, ids: &[Id], mesh: &Mesh) {
    let group_name = element_group_name(&mesh.element_group_names[group_id]);
    lines.push(format!("*Elset, elset={group_name}"));
    lines.extend(slice_ids(ids, 16, ","));
}

fn element_line(element_id: Id, ids: &[Id]) -> String {
    format!(
        "{element_id},{}",
        ids.iter()
            .map(ToString::to_string)
            .collect::<Vec<_>>()
            .join(",")
    )
}

#[cfg(test)]
mod tests {
    use crate::exporters::ids_in_order;
    use crate::model::Element;

    use super::{shell_mapping, solid_mapping};

    #[test]
    fn abaqus_prism_mapping_repeats_nodes() {
        let element = Element::new(1, vec![1, 2, 3, 4, 5, 6]);
        assert_eq!(
            ids_in_order(&element, solid_mapping(&element).unwrap()).unwrap(),
            vec![1, 2, 3, 3, 4, 5, 6, 6]
        );
    }

    #[test]
    fn abaqus_tri_mapping_repeats_last_node() {
        let element = Element::new(1, vec![1, 2, 3]);
        assert_eq!(
            ids_in_order(&element, shell_mapping(&element).unwrap()).unwrap(),
            vec![1, 2, 3, 3]
        );
    }
}
