use std::collections::BTreeSet;
use std::path::Path;

use crate::model::{Element, Id, Mesh};

use super::{
    element_group_name, ensure_output_folder, format_e6, ids_in_order, slice_ids, write_lines,
    ExportError, ExportResult, ExportedFiles, Flac3dOptions,
};

pub fn export(
    mesh: &Mesh,
    output_folder: impl AsRef<Path>,
    output_file_name: &str,
    options: Flac3dOptions,
) -> ExportResult<ExportedFiles> {
    let output_folder = output_folder.as_ref();
    ensure_output_folder(output_folder)?;
    let _ = options.check_input_data;

    let mut files = ExportedFiles::default();
    let grid = create_grid_file(mesh, output_folder, output_file_name)?;
    files.push(grid);
    if let Some(geom) = create_geom_file(mesh, output_folder, output_file_name)? {
        files.push(geom);
    }
    Ok(files)
}

pub fn zone_mapping(element: &Element) -> Option<(&'static str, &'static [usize])> {
    match element.node_ids.len() {
        8 => Some(("Z B8", &[1, 2, 4, 5, 3, 8, 6, 7])),
        6 => Some(("Z W6", &[1, 3, 4, 2, 6, 5])),
        5 => Some(("Z P5", &[1, 2, 4, 5, 3])),
        4 => Some(("Z T4", &[1, 2, 3, 4])),
        _ => None,
    }
}

pub fn face_mapping(element: &Element) -> Option<(&'static str, &'static [usize])> {
    match element.node_ids.len() {
        4 => Some(("F Q4", &[1, 2, 3, 4])),
        3 => Some(("F T3", &[1, 2, 3])),
        _ => None,
    }
}

fn create_grid_file(
    mesh: &Mesh,
    output_folder: &Path,
    output_file_name: &str,
) -> ExportResult<std::path::PathBuf> {
    let mut lines = vec![
        "*".to_owned(),
        "* FLAC3D Mesh generated by MidasGtsExporter v20180405".to_owned(),
        "*".to_owned(),
        "* GRIDPOINTS".to_owned(),
    ];

    let mut output_node_ids = BTreeSet::new();
    for element in mesh.elements_3d.values().chain(mesh.elements_2d.values()) {
        output_node_ids.extend(element.node_ids.iter().copied());
    }
    for node_id in output_node_ids {
        let node = mesh
            .nodes
            .get(&node_id)
            .ok_or(ExportError::MissingNode { node_id })?;
        lines.push(format!(
            "G {} {} {} {}",
            node.id,
            format_e6(node.x),
            format_e6(node.y),
            format_e6(node.z)
        ));
    }

    if !mesh.elements_3d.is_empty() {
        lines.push("* ZONES".to_owned());
        for element in mesh.elements_3d.values() {
            if let Some((prefix, order)) = zone_mapping(element) {
                let ids = ids_in_order(element, order)?;
                lines.push(format!("{} {} {}", prefix, element.id, join_space(&ids)));
            }
        }
    }

    if !mesh.element_3d_groups.is_empty() {
        lines.push("* ZONE GROUPS".to_owned());
        for (group_id, ids) in &mesh.element_3d_groups {
            let group_name = element_group_name(&mesh.element_group_names[group_id]);
            lines.push(format!("ZGROUP \"{group_name}\" SLOT 1 "));
            lines.extend(slice_ids(ids, 20, " "));
        }
    }

    if !mesh.elements_2d.is_empty() {
        lines.push("* FACES".to_owned());
        for element in mesh.elements_2d.values() {
            if let Some((prefix, order)) = face_mapping(element) {
                let ids = ids_in_order(element, order)?;
                lines.push(format!("{} {} {}", prefix, element.id, join_space(&ids)));
            }
        }
    }

    if !mesh.element_2d_groups.is_empty() {
        lines.push("* FACE GROUPS".to_owned());
        for (group_id, ids) in &mesh.element_2d_groups {
            let group_name = element_group_name(&mesh.element_group_names[group_id]);
            lines.push(format!("FGROUP \"{group_name}\" SLOT 2 "));
            lines.extend(slice_ids(ids, 20, " "));
        }
    }

    write_lines(
        output_folder.join(format!("{output_file_name}_Mesh.f3grid")),
        lines,
    )
}

fn create_geom_file(
    mesh: &Mesh,
    output_folder: &Path,
    output_file_name: &str,
) -> ExportResult<Option<std::path::PathBuf>> {
    if mesh.elements_1d.is_empty() || mesh.element_1d_groups.is_empty() {
        return Ok(None);
    }

    let mut lines = vec![
        "ITASCA GEOMETRY3D".to_owned(),
        ";".to_owned(),
        "NODES".to_owned(),
    ];
    for element in mesh.elements_1d.values() {
        for node_id in &element.node_ids {
            let node = mesh
                .nodes
                .get(node_id)
                .ok_or(ExportError::MissingNode { node_id: *node_id })?;
            lines.push(format!(
                "{} ({},{},{})",
                node.id,
                format_e6(node.x),
                format_e6(node.y),
                format_e6(node.z)
            ));
        }
    }

    lines.push("EDGES".to_owned());
    for (group_id, element_ids) in &mesh.element_1d_groups {
        let group_name = element_group_name(&mesh.element_group_names[group_id]);
        lines.push(format!("GROUP \"Geom\" \"{group_name}\""));
        for element_id in element_ids {
            let element = mesh
                .elements_1d
                .get(element_id)
                .ok_or(ExportError::MissingElement {
                    element_id: *element_id,
                })?;
            let ids = ids_in_order(element, &[1, 2])?;
            lines.push(format!("{} {} {}", element.id, ids[0], ids[1]));
        }
    }

    write_lines(
        output_folder.join(format!("{output_file_name}_Geom.geom")),
        lines,
    )
    .map(Some)
}

fn join_space(ids: &[Id]) -> String {
    ids.iter()
        .map(ToString::to_string)
        .collect::<Vec<_>>()
        .join(" ")
}

#[cfg(test)]
mod tests {
    use crate::model::Element;

    use super::{face_mapping, zone_mapping};
    use crate::exporters::ids_in_order;

    #[test]
    fn flac3d_zone_mapping_orders_nodes() {
        let element = Element::new(1, vec![1, 2, 3, 4, 5, 6, 7, 8]);
        let (prefix, order) = zone_mapping(&element).unwrap();
        assert_eq!(prefix, "Z B8");
        assert_eq!(
            ids_in_order(&element, order).unwrap(),
            vec![1, 2, 4, 5, 3, 8, 6, 7]
        );
    }

    #[test]
    fn flac3d_face_mapping_orders_nodes() {
        let element = Element::new(1, vec![1, 2, 3]);
        let (prefix, order) = face_mapping(&element).unwrap();
        assert_eq!(prefix, "F T3");
        assert_eq!(ids_in_order(&element, order).unwrap(), vec![1, 2, 3]);
    }
}
