use std::path::Path;

use crate::model::{Element, GroupMap, Id, Mesh};

use super::{
    element_group_name, ensure_output_folder, format_e6, ids_in_order, node_group_name, slice_ids,
    write_lines, ExportError, ExportResult, ExportedFiles, LsDynaOptions,
};

const SEGMENT_GROUP_NAME_PREFIX: &str = "eset_segment_";

pub fn export(
    mesh: &Mesh,
    output_folder: impl AsRef<Path>,
    output_file_name: &str,
    options: LsDynaOptions,
) -> ExportResult<ExportedFiles> {
    let output_folder = output_folder.as_ref();
    ensure_output_folder(output_folder)?;
    let _ = options.check_input_data;

    let split = split_2d_groups(mesh);
    let names = file_names(output_file_name);
    let mut files = ExportedFiles::default();

    let main_path = output_folder.join(&names.main);
    if !main_path.is_file() || options.overwrite_main_output_file {
        files.push(write_lines(
            main_path,
            create_main_lines(mesh, output_file_name, &names, &split),
        )?);
    }

    files.push(write_lines(
        output_folder.join(&names.part),
        create_part_lines(mesh, output_file_name, &names, &split),
    )?);
    files.push(write_lines(
        output_folder.join(&names.node),
        create_node_lines(mesh, output_file_name),
    )?);
    files.push(write_lines(
        output_folder.join(&names.element),
        create_element_lines(mesh, output_file_name, &split)?,
    )?);
    if !mesh.node_groups.is_empty() {
        files.push(write_lines(
            output_folder.join(&names.node_list),
            create_node_list_lines(mesh, output_file_name),
        )?);
    }
    if !split.segment_2d_groups.is_empty() {
        files.push(write_lines(
            output_folder.join(&names.segment),
            create_segment_lines(mesh, output_file_name, &split)?,
        )?);
    }

    Ok(files)
}

pub fn solid_mapping(element: &Element) -> Option<&'static [usize]> {
    match element.node_ids.len() {
        8 => Some(&[1, 2, 3, 4, 5, 6, 7, 8]),
        6 => Some(&[3, 2, 5, 6, 1, 1, 4, 4]),
        5 => Some(&[1, 2, 3, 4, 5, 5, 5, 5]),
        4 => Some(&[1, 2, 3, 4, 4, 4, 4, 4]),
        _ => None,
    }
}

pub fn shell_mapping(element: &Element) -> Option<&'static [usize]> {
    match element.node_ids.len() {
        4 => Some(&[1, 2, 3, 4]),
        3 => Some(&[1, 2, 3, 3]),
        _ => None,
    }
}

fn create_main_lines(
    mesh: &Mesh,
    output_file_name: &str,
    names: &FileNames,
    split: &Split2dGroups,
) -> Vec<String> {
    let mut lines = vec![
        "$".to_owned(),
        "$ LS-DYNA Mesh generated by MidasGtsExporter v20180405".to_owned(),
        "$".to_owned(),
        "*KEYWORD".to_owned(),
        "*TITLE".to_owned(),
        "LS-DYNA Mesh".to_owned(),
        "$".to_owned(),
        "$ ---------- Control option ---------------------------------------".to_owned(),
        "*CONTROL_SOLID".to_owned(),
        ",,4,1".to_owned(),
        String::new(),
        "*CONTROL_TERMINATION".to_owned(),
        "1.0,,,,1e+08".to_owned(),
        "$".to_owned(),
        "$ ---------- Database option ---------------------------------------".to_owned(),
        "*DATABASE_BINARY_D3PLOT".to_owned(),
        "0.5".to_owned(),
        "*DATABASE_BINARY_D3THDT".to_owned(),
        "0.1".to_owned(),
        "$".to_owned(),
        "$ ---------- Material Definition ---------------------------------------".to_owned(),
        "*MAT_ELASTIC_TITLE".to_owned(),
        "mat01".to_owned(),
        "1,10.0".to_owned(),
    ];
    if !mesh.element_3d_groups.is_empty() {
        lines.extend([
            "$ ---------- Sections Definition ---------------------------------------".to_owned(),
            "*SECTION_SOLID_TITLE".to_owned(),
            "section01".to_owned(),
            "1,1,0".to_owned(),
        ]);
    }
    if !split.common_2d_groups.is_empty() {
        lines.extend([
            "*SECTION_SHELL_TITLE".to_owned(),
            "section02".to_owned(),
            "2,2,1,2,1,,,1".to_owned(),
            "1,1,1,1".to_owned(),
        ]);
    }
    lines.extend([
        "$".to_owned(),
        "$ ---------- Part Definition ---------------------------------------".to_owned(),
        "*INCLUDE".to_owned(),
        names.part.clone(),
        "$".to_owned(),
        "*END".to_owned(),
    ]);
    let _ = output_file_name;
    lines
}

fn create_part_lines(
    mesh: &Mesh,
    output_file_name: &str,
    names: &FileNames,
    split: &Split2dGroups,
) -> Vec<String> {
    let mut lines = vec![
        "$".to_owned(),
        format!("$ LS-DYNA Mesh generated by MidasGtsExporter v20180405 for {output_file_name}.k"),
        "$".to_owned(),
        "*KEYWORD".to_owned(),
        "$ ---------- Part Definition ---------------------------------------".to_owned(),
    ];

    for group_id in mesh.element_3d_groups.keys() {
        let group_name = element_group_name(&mesh.element_group_names[group_id]);
        lines.extend(["*PART".to_owned(), group_name, format!("{group_id},1,1")]);
    }
    for group_id in split.common_2d_groups.keys() {
        let group_name = element_group_name(&mesh.element_group_names[group_id]);
        lines.extend(["*PART".to_owned(), group_name, format!("{group_id},2,1")]);
    }

    lines.extend([
        "$".to_owned(),
        "$".to_owned(),
        "$ ---------- Node Definition ---------------------------------------".to_owned(),
        format!("$ NodeCount: {}", mesh.nodes.len()),
        "*INCLUDE".to_owned(),
        names.node.clone(),
        "$".to_owned(),
        "$ ---------- Element Definition ------------------------------------".to_owned(),
    ]);
    for (group_id, ids) in &mesh.element_3d_groups {
        let group_name = element_group_name(&mesh.element_group_names[group_id]);
        lines.push(format!(
            "$ ELEMENT_SOLID, PartID: {group_id}, PartName: {group_name}, ElemCount: {}",
            ids.len()
        ));
    }
    for (group_id, ids) in &split.common_2d_groups {
        let group_name = element_group_name(&mesh.element_group_names[group_id]);
        lines.push(format!(
            "$ ELEMENT_SHELL, PartID: {group_id}, PartName: {group_name}, ElemCount: {}",
            ids.len()
        ));
    }
    lines.extend(["*INCLUDE".to_owned(), names.element.clone()]);

    if !mesh.node_groups.is_empty() {
        lines.extend([
            "$".to_owned(),
            "$ ---------- NodeList Definition ---------------------------------".to_owned(),
        ]);
        for (group_id, ids) in &mesh.node_groups {
            let group_name = node_group_name(&mesh.node_group_names[group_id]);
            lines.push(format!(
                "$ NodeListID: {group_id}, SetName: {group_name}, NodeCount: {}",
                ids.len()
            ));
        }
        lines.extend(["*INCLUDE".to_owned(), names.node_list.clone()]);
    }

    if !split.segment_2d_groups.is_empty() {
        lines.extend([
            "$".to_owned(),
            "$ ---------- Segment Definition ----------------------------------".to_owned(),
        ]);
        for (group_id, ids) in &split.segment_2d_groups {
            let group_name = element_group_name(&mesh.element_group_names[group_id]);
            lines.push(format!(
                "$ SegmentID: {group_id}, SetName: {group_name}, ElemCount: {}",
                ids.len()
            ));
        }
        lines.extend(["*INCLUDE".to_owned(), names.segment.clone()]);
    }

    lines.extend(["$".to_owned(), "*END".to_owned()]);
    lines
}

fn create_node_lines(mesh: &Mesh, output_file_name: &str) -> Vec<String> {
    let mut lines = vec![
        "$".to_owned(),
        format!("$ Node data for {output_file_name}.k"),
        "$".to_owned(),
        "*KEYWORD".to_owned(),
        "*NODE".to_owned(),
    ];
    for node in mesh.nodes.values() {
        lines.push(format!(
            "{},{},{},{}",
            node.id,
            format_e6(node.x),
            format_e6(node.y),
            format_e6(node.z)
        ));
    }
    lines.push("*END".to_owned());
    lines
}

fn create_element_lines(
    mesh: &Mesh,
    output_file_name: &str,
    split: &Split2dGroups,
) -> ExportResult<Vec<String>> {
    let mut lines = vec![
        "$".to_owned(),
        format!("$ Element data for {output_file_name}.k"),
        "$".to_owned(),
        "*KEYWORD".to_owned(),
    ];

    if !mesh.element_3d_groups.is_empty() {
        lines.push("*ELEMENT_SOLID".to_owned());
        for (group_id, element_ids) in &mesh.element_3d_groups {
            append_solid_group(&mut lines, mesh, *group_id, element_ids)?;
        }
    }

    if !split.common_2d_groups.is_empty() {
        lines.push("*ELEMENT_SHELL".to_owned());
        for (group_id, element_ids) in &split.common_2d_groups {
            append_shell_group(&mut lines, mesh, *group_id, element_ids)?;
        }
    }

    lines.push("*END".to_owned());
    Ok(lines)
}

fn append_solid_group(
    lines: &mut Vec<String>,
    mesh: &Mesh,
    part_id: Id,
    element_ids: &[Id],
) -> ExportResult<()> {
    for (label, node_count) in [("HEXA", 8), ("PRISM", 6), ("PYRAM", 5), ("TETRA", 4)] {
        lines.extend(["$".to_owned(), format!("$ {label}")]);
        for element_id in element_ids {
            let element = mesh
                .elements_3d
                .get(element_id)
                .ok_or(ExportError::MissingElement {
                    element_id: *element_id,
                })?;
            if element.node_ids.len() == node_count {
                lines.push(part_element_line(
                    element.id,
                    part_id,
                    &ids_in_order(element, solid_mapping(element).unwrap())?,
                ));
            }
        }
    }
    lines.extend(["$".to_owned(), "$".to_owned()]);
    Ok(())
}

fn append_shell_group(
    lines: &mut Vec<String>,
    mesh: &Mesh,
    part_id: Id,
    element_ids: &[Id],
) -> ExportResult<()> {
    for (label, node_count) in [("RECT", 4), ("TRIA", 3)] {
        lines.extend(["$".to_owned(), format!("$ {label}")]);
        for element_id in element_ids {
            let element = mesh
                .elements_2d
                .get(element_id)
                .ok_or(ExportError::MissingElement {
                    element_id: *element_id,
                })?;
            if element.node_ids.len() == node_count {
                lines.push(part_element_line(
                    element.id,
                    part_id,
                    &ids_in_order(element, shell_mapping(element).unwrap())?,
                ));
            }
        }
    }
    lines.extend(["$".to_owned(), "$".to_owned()]);
    Ok(())
}

fn create_node_list_lines(mesh: &Mesh, output_file_name: &str) -> Vec<String> {
    let mut lines = vec![
        "$".to_owned(),
        format!("$ NodeList data for {output_file_name}.k"),
        "$".to_owned(),
        "*KEYWORD".to_owned(),
    ];
    for (group_id, ids) in &mesh.node_groups {
        let group_name = node_group_name(&mesh.node_group_names[group_id]);
        lines.extend([
            "*SET_NODE_LIST_TITLE".to_owned(),
            group_name,
            format!("{group_id},,,,,MECH"),
        ]);
        lines.extend(slice_ids(ids, 8, ","));
        lines.extend(["$".to_owned(), "$".to_owned()]);
    }
    lines.push("*END".to_owned());
    lines
}

fn create_segment_lines(
    mesh: &Mesh,
    output_file_name: &str,
    split: &Split2dGroups,
) -> ExportResult<Vec<String>> {
    let mut lines = vec![
        "$".to_owned(),
        format!("$ Segment data for {output_file_name}.k"),
        "$".to_owned(),
        "*KEYWORD".to_owned(),
    ];
    for (group_id, ids) in &split.segment_2d_groups {
        let group_name = element_group_name(&mesh.element_group_names[group_id]);
        lines.extend([
            "*SET_SEGMENT_TITLE".to_owned(),
            group_name,
            format!("{group_id},,,,,MECH"),
        ]);
        for element_id in ids {
            let element = mesh
                .elements_2d
                .get(element_id)
                .ok_or(ExportError::MissingElement {
                    element_id: *element_id,
                })?;
            lines.push(
                ids_in_order(element, shell_mapping(element).unwrap())?
                    .iter()
                    .map(ToString::to_string)
                    .collect::<Vec<_>>()
                    .join(","),
            );
        }
        lines.extend(["$".to_owned(), "$".to_owned()]);
    }
    lines.push("*END".to_owned());
    Ok(lines)
}

fn part_element_line(element_id: Id, part_id: Id, ids: &[Id]) -> String {
    format!(
        "{element_id},{part_id},{}",
        ids.iter()
            .map(ToString::to_string)
            .collect::<Vec<_>>()
            .join(",")
    )
}

fn split_2d_groups(mesh: &Mesh) -> Split2dGroups {
    let mut split = Split2dGroups::default();
    for (group_id, ids) in &mesh.element_2d_groups {
        let group_name = element_group_name(&mesh.element_group_names[group_id]);
        if group_name
            .to_ascii_lowercase()
            .starts_with(SEGMENT_GROUP_NAME_PREFIX)
        {
            split.segment_2d_groups.insert(*group_id, ids.clone());
        } else {
            split.common_2d_groups.insert(*group_id, ids.clone());
        }
    }
    split
}

#[derive(Debug, Clone, Default)]
struct Split2dGroups {
    common_2d_groups: GroupMap,
    segment_2d_groups: GroupMap,
}

fn file_names(output_file_name: &str) -> FileNames {
    FileNames {
        main: format!("{output_file_name}.k"),
        part: format!("{output_file_name}_Part.k"),
        node: format!("{output_file_name}_Node.k"),
        element: format!("{output_file_name}_Elem.k"),
        node_list: format!("{output_file_name}_NodeList.k"),
        segment: format!("{output_file_name}_Segment.k"),
    }
}

#[derive(Debug, Clone)]
struct FileNames {
    main: String,
    part: String,
    node: String,
    element: String,
    node_list: String,
    segment: String,
}

#[cfg(test)]
mod tests {
    use std::fs;

    use tempfile::tempdir;

    use crate::exporters::ids_in_order;
    use crate::model::Element;

    use super::{export, shell_mapping, solid_mapping, LsDynaOptions};

    #[test]
    fn lsdyna_prism_mapping_reorders_and_repeats_nodes() {
        let element = Element::new(1, vec![1, 2, 3, 4, 5, 6]);
        assert_eq!(
            ids_in_order(&element, solid_mapping(&element).unwrap()).unwrap(),
            vec![3, 2, 5, 6, 1, 1, 4, 4]
        );
    }

    #[test]
    fn lsdyna_tri_mapping_repeats_last_node() {
        let element = Element::new(1, vec![1, 2, 3]);
        assert_eq!(
            ids_in_order(&element, shell_mapping(&element).unwrap()).unwrap(),
            vec![1, 2, 3, 3]
        );
    }

    #[test]
    fn lsdyna_main_file_honors_overwrite_option() {
        let mesh = crate::exporters::test_support::fixture_mesh("GtsModel_Coarse.fpn");
        let dir = tempdir().unwrap();
        let main = dir.path().join("mesh.k");
        fs::write(&main, "KEEP").unwrap();

        export(
            &mesh,
            dir.path(),
            "mesh",
            LsDynaOptions {
                check_input_data: true,
                overwrite_main_output_file: false,
            },
        )
        .unwrap();
        assert_eq!(fs::read_to_string(&main).unwrap(), "KEEP");

        export(
            &mesh,
            dir.path(),
            "mesh",
            LsDynaOptions {
                check_input_data: true,
                overwrite_main_output_file: true,
            },
        )
        .unwrap();
        assert!(fs::read_to_string(&main).unwrap().contains("*KEYWORD"));
    }
}
